### ISSUE TITLE
Problems with the code

### ISSUE THREAD

**Issue by antton** [estebandelaf/odsPhpGenerator#3]
Hi, 

Could you add an example as helloworld or somethings similar?

When I try to use the http://odsphpgenerator.lapinator.net/download/ examples they don't work, I always get the  Fatal error: Class 'ods' not found in 

I'm adding properly the ods.php file but I'm not sure if I'm doing well.

Thanks for your time!

**Comment by estebandelaf** [comment]
Hi, you need to include the class with the namespace if you are not specifing "use":

    $ods = new \odsphpgenerator\ods();

I added a "Hello World!" example in the repository. Additionally you can look into the code in my ODS class that use this project, specifically the generate method in https://github.com/SowerPHP/extension-general/blob/master/Utility/Spreadsheet/ODS.php

Greetings!

**Comment by antton** [comment]
Gracias por la información!
Ya lo he conseguido tras leer todo lo comentado.

Un saludo.
